name: my_first_bank
description: Esta es una applicacion Movil construida en flutter, con Clean Arquitecture y Bloc para Todo 1

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1


  cupertino_icons: ^1.0.0
  #  #  BLOCs
  #  dash: ^0.5.5
  rxdart: ^0.23.1
  http: ^0.12.2
  connectivity: ^0.4.8+2
  shared_preferences: ^0.5.12+4
  #  Database
  sembast: ^2.4.1+1
  encrypt: ^4.0.0
  crypto: ^2.1.3
  path_provider: ^1.6.5
  #  URL Launcher
  url_launcher: ^5.4.2
  #  Package Info
  package_info: ^0.4.0+16
  #  ReCase
  recase: ^3.0.0
  #  INTL
  intl: ^0.16.0
  cached_network_image: ^2.5.0
  pull_to_refresh: ^1.5.8
  #  SVG
  flutter_svg: ^0.19.0
  #Autocomplete textfield
  flutter_typeahead: ^1.9.1
  # Local Notifications
  #For select image from gallery or camera
  image_picker: ^0.6.7+21

dev_dependencies:
  flutter_test:
    sdk: flutter
  #  build_runner: ^1.7.2
  #  dash_generator: ^0.5.5
  mockito: ^4.1.1
  effective_dart: ^1.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family:  Plataforma
      fonts:
        - asset: fonts/Plataforma.ttf
    - family:  Open Sans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-BoldItalic.ttf
        - asset: fonts/OpenSans-ExtraBold.ttf
        - asset: fonts/OpenSans-ExtraBoldItalic.ttf
        - asset: fonts/OpenSans-Italic.ttf
        - asset: fonts/OpenSans-Light.ttf
        - asset: fonts/OpenSans-LightItalic.ttf
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
        - asset: fonts/OpenSans-SemiBoldItalic.ttf
